//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectorViewer.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VectorViewer.Services.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primitive converter of type {0} not registered.
        /// </summary>
        internal static string Converter_Not_Registered {
            get {
                return ResourceManager.GetString("Converter_Not_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert primitive.
        /// </summary>
        internal static string Failed_To_Convert_Primitive {
            get {
                return ResourceManager.GetString("Failed_To_Convert_Primitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the dto for primitive.
        /// </summary>
        internal static string Failed_To_Get_Dto {
            get {
                return ResourceManager.GetString("Failed_To_Get_Dto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file found along the path: {0}.
        /// </summary>
        internal static string JsonDataSourceParser_file_not_found {
            get {
                return ResourceManager.GetString("JsonDataSourceParser_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No converter registered for the primitive type {0}.
        /// </summary>
        internal static string No_Converter_Registered_For_Type {
            get {
                return ResourceManager.GetString("No_Converter_Registered_For_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data source parser registered for file {0}.
        /// </summary>
        internal static string No_Data_Source_Parser_Registered {
            get {
                return ResourceManager.GetString("No_Data_Source_Parser_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primitive type not specified.
        /// </summary>
        internal static string Primitive_Type_Not_Specified {
            get {
                return ResourceManager.GetString("Primitive_Type_Not_Specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primitive type not supplied.
        /// </summary>
        internal static string Primitive_Type_Not_Supplied {
            get {
                return ResourceManager.GetString("Primitive_Type_Not_Supplied", resourceCulture);
            }
        }
    }
}
